export type Product = {
  id: string;
  name: string;
  category: string;
  rxRequired: boolean;
  manufacturer: string;
  price: number;
  stock: number;
  status: "Active" | "Inactive";
};

export const products: Product[] = [
  {
    id: "1",
    name: "Amoxicillin 500mg",
    category: "Antibiotics",
    rxRequired: true,
    manufacturer: "PharmaCorp",
    price: 15.99,
    stock: 450,
    status: "Active",
  },
  {
    id: "2",
    name: "Ibuprofen 200mg",
    category: "Pain Relief",
    rxRequired: false,
    manufacturer: "GenericHealth",
    price: 8.5,
    stock: 1200,
    status: "Active",
  },
  {
    id: "3",
    name: "Lisinopril 10mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "HeartCare",
    price: 12.0,
    stock: 30,
    status: "Active",
  },
  {
    id: "4",
    name: "Cetirizine 10mg",
    category: "Allergy",
    rxRequired: false,
    manufacturer: "AllerStop",
    price: 18.25,
    stock: 800,
    status: "Active",
  },
  {
    id: "5",
    name: "Metformin 500mg",
    category: "Diabetes",
    rxRequired: true,
    manufacturer: "SugarFree",
    price: 10.5,
    stock: 200,
    status: "Active",
  },
  {
    id: "6",
    name: "Vitamin D3 1000IU",
    category: "Vitamins",
    rxRequired: false,
    manufacturer: "NatureBest",
    price: 11.99,
    stock: 60,
    status: "Active",
  },
  {
    id: "7",
    name: "Omeprazole 20mg",
    category: "Gastrointestinal",
    rxRequired: false,
    manufacturer: "BioLife",
    price: 14.5,
    stock: 300,
    status: "Active",
  },
  {
    id: "8",
    name: "Atorvastatin 20mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "MedSource",
    price: 22.0,
    stock: 150,
    status: "Active",
  },
  {
    id: "9",
    name: "Albuterol Inhaler",
    category: "Respiratory",
    rxRequired: true,
    manufacturer: "AeroMed",
    price: 35.0,
    stock: 45,
    status: "Active",
  },
  {
    id: "10",
    name: "Hydrocortisone Cream",
    category: "Dermatology",
    rxRequired: false,
    manufacturer: "SkinCare+",
    price: 9.25,
    stock: 500,
    status: "Active",
  },
  {
    id: "11",
    name: "Azithromycin 250mg",
    category: "Antibiotics",
    rxRequired: true,
    manufacturer: "PharmaCorp",
    price: 28.5,
    stock: 100,
    status: "Active",
  },
  {
    id: "12",
    name: "Amlodipine 5mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "HeartCare",
    price: 11.0,
    stock: 210,
    status: "Active",
  },
  {
    id: "13",
    name: "Paracetamol 500mg",
    category: "Pain Relief",
    rxRequired: false,
    manufacturer: "GenericHealth",
    price: 5.99,
    stock: 2000,
    status: "Active",
  },
  {
    id: "14",
    name: "Sertraline 50mg",
    category: "Mental Health",
    rxRequired: true,
    manufacturer: "MindWell",
    price: 19.99,
    stock: 85,
    status: "Active",
  },
  {
    id: "15",
    name: "Loratadine 10mg",
    category: "Allergy",
    rxRequired: false,
    manufacturer: "AllerStop",
    price: 12.4,
    stock: 600,
    status: "Active",
  },
  {
    id: "16",
    name: "Prednisone 5mg",
    category: "Anti-inflammatory",
    rxRequired: true,
    manufacturer: "BioLife",
    price: 7.5,
    stock: 120,
    status: "Active",
  },
  {
    id: "17",
    name: "Simvastatin 20mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "MedSource",
    price: 14.0,
    stock: 95,
    status: "Active",
  },
  {
    id: "18",
    name: "Guaifenesin 400mg",
    category: "Respiratory",
    rxRequired: false,
    manufacturer: "CoughFree",
    price: 11.2,
    stock: 400,
    status: "Active",
  },
  {
    id: "19",
    name: "Ciprofloxacin 500mg",
    category: "Antibiotics",
    rxRequired: true,
    manufacturer: "PharmaCorp",
    price: 32.0,
    stock: 55,
    status: "Active",
  },
  {
    id: "20",
    name: "Naproxen 220mg",
    category: "Pain Relief",
    rxRequired: false,
    manufacturer: "GenericHealth",
    price: 9.99,
    stock: 750,
    status: "Active",
  },
  {
    id: "21",
    name: "Gabapentin 300mg",
    category: "Neurology",
    rxRequired: true,
    manufacturer: "NerveRelief",
    price: 25.5,
    stock: 130,
    status: "Active",
  },
  {
    id: "22",
    name: "Ranitidine 150mg",
    category: "Gastrointestinal",
    rxRequired: false,
    manufacturer: "BioLife",
    price: 16.75,
    stock: 0,
    status: "Inactive",
  },
  {
    id: "23",
    name: "Losartan 50mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "HeartCare",
    price: 13.5,
    stock: 310,
    status: "Active",
  },
  {
    id: "24",
    name: "Melatonin 5mg",
    category: "Sleep Aid",
    rxRequired: false,
    manufacturer: "NatureBest",
    price: 14.99,
    stock: 250,
    status: "Active",
  },
  {
    id: "25",
    name: "Glipizide 5mg",
    category: "Diabetes",
    rxRequired: true,
    manufacturer: "SugarFree",
    price: 11.25,
    stock: 180,
    status: "Active",
  },
  {
    id: "26",
    name: "Magnesium 250mg",
    category: "Vitamins",
    rxRequired: false,
    manufacturer: "NatureBest",
    price: 10.0,
    stock: 400,
    status: "Active",
  },
  {
    id: "27",
    name: "Furosemide 40mg",
    category: "Cardiovascular",
    rxRequired: true,
    manufacturer: "MedSource",
    price: 8.0,
    stock: 140,
    status: "Active",
  },
  {
    id: "28",
    name: "Clarithromycin 500mg",
    category: "Antibiotics",
    rxRequired: true,
    manufacturer: "PharmaCorp",
    price: 45.0,
    stock: 25,
    status: "Active",
  },
  {
    id: "29",
    name: "Escitalopram 10mg",
    category: "Mental Health",
    rxRequired: true,
    manufacturer: "MindWell",
    price: 21.0,
    stock: 110,
    status: "Active",
  },
  {
    id: "30",
    name: "Aspirin 81mg",
    category: "Pain Relief",
    rxRequired: false,
    manufacturer: "GenericHealth",
    price: 6.5,
    stock: 1500,
    status: "Active",
  },
];
